// File generated by Firebase project setup.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByGYtwCZMk1GM0lHnVLx9_PPafbrXogYA',
    appId: '1:424765276744:web:3215bf6b863d4c134dce7d',
    messagingSenderId: '424765276744',
    projectId: 'daily-littlebit0',
    authDomain: 'daily-littlebit0.firebaseapp.com',
    storageBucket: 'daily-littlebit0.firebasestorage.app',
    measurementId: 'G-W8L7VZ5M2W',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByGYtwCZMk1GM0lHnVLx9_PPafbrXogYA',
    appId: '1:424765276744:web:3215bf6b863d4c134dce7d',
    messagingSenderId: '424765276744',
    projectId: 'daily-littlebit0',
    authDomain: 'daily-littlebit0.firebaseapp.com',
    storageBucket: 'daily-littlebit0.firebasestorage.app',
    measurementId: 'G-W8L7VZ5M2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuqMc_4B1qWz5ZdqHF-ocGg35eIz5FwCQ',
    appId: '1:424765276744:android:a5d064eb7f2800694dce7d',
    messagingSenderId: '424765276744',
    projectId: 'daily-littlebit0',
    storageBucket: 'daily-littlebit0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDahYt4Y7AtdWwU7D2zY5dLvhUYCVNplQ',
    appId: '1:424765276744:ios:a28c3867afb0cf774dce7d',
    messagingSenderId: '424765276744',
    projectId: 'daily-littlebit0',
    storageBucket: 'daily-littlebit0.firebasestorage.app',
    iosBundleId: 'com.littlebit0.daily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDahYt4Y7AtdWwU7D2zY5dLvhUYCVNplQ',
    appId: '1:424765276744:ios:739b1093145940b24dce7d',
    messagingSenderId: '424765276744',
    projectId: 'daily-littlebit0',
    storageBucket: 'daily-littlebit0.firebasestorage.app',
    iosBundleId: 'com.littlebit0.daily.macos',
  );

  static bool get isPlaceholder => false;
}
