import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../settings/app_settings.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('ko'),
    Locale('en'),
    Locale('ja'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('ko'));
  }

  String get languageCode {
    if (locale.languageCode == 'zh') return 'zh_Hant';
    return locale.languageCode;
  }

  String text(String korean, {Map<String, Object>? args}) {
    var translated = _translations[languageCode]?[korean] ?? korean;
    for (final entry in (args ?? const <String, Object>{}).entries) {
      translated = translated.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return translated;
  }

  String languageName(AppLanguage language) => switch (language) {
    AppLanguage.system => text('시스템 설정에 따름'),
    AppLanguage.korean => '한국어',
    AppLanguage.english => 'English',
    AppLanguage.japanese => '日本語',
    AppLanguage.traditionalChinese => '繁體中文',
  };

  String themeName(AppThemeMode mode) => switch (mode) {
    AppThemeMode.system => text('자동'),
    AppThemeMode.light => text('화이트'),
    AppThemeMode.dark => text('다크'),
  };

  String navigationName(MonthNavigationMode mode) => switch (mode) {
    MonthNavigationMode.horizontal => text('좌우 슬라이드'),
    MonthNavigationMode.vertical => text('상하 스크롤'),
  };

  String textSizeName(AppTextSize size) => switch (size) {
    AppTextSize.basic => text('기본'),
    AppTextSize.large => text('크게'),
    AppTextSize.extraLarge => text('더 크게'),
  };

  String calendarViewName(CalendarViewMode mode) => switch (mode) {
    CalendarViewMode.week => text('주간'),
    CalendarViewMode.month => text('월간'),
    CalendarViewMode.day => text('일간'),
  };

  String compactCalendarViewName(CalendarViewMode mode) {
    if (languageCode == 'ko') {
      return switch (mode) {
        CalendarViewMode.week => '주',
        CalendarViewMode.month => '월',
        CalendarViewMode.day => '일',
      };
    }
    return switch (mode) {
      CalendarViewMode.week => text('주 보기'),
      CalendarViewMode.month => text('월 보기'),
      CalendarViewMode.day => text('일 보기'),
    };
  }

  String lockMethodName(AppLockMethod method) => switch (method) {
    AppLockMethod.noPin => text('PIN 없이 잠금'),
    AppLockMethod.appPin => text('PIN 잠금'),
    AppLockMethod.system => text('시스템 잠금 비밀번호'),
  };

  String categoryName({required String id, required String label}) {
    if (id == 'basic' && label == '기본') {
      return text('기본');
    }
    if (id == 'holiday') {
      return text('공휴일');
    }
    return label;
  }

  String holidayTitle(String title) {
    return title.split(' · ').map((part) => text(part)).join(' · ');
  }

  String eventTitle(String title, {required bool holiday}) {
    return holiday ? holidayTitle(title) : title;
  }
}

extension AppLocalizationContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String korean, {Map<String, Object>? args}) =>
      l10n.text(korean, args: args);
}

Locale? localeForLanguage(AppLanguage language) => switch (language) {
  AppLanguage.system => null,
  AppLanguage.korean => const Locale('ko'),
  AppLanguage.english => const Locale('en'),
  AppLanguage.japanese => const Locale('ja'),
  AppLanguage.traditionalChinese => const Locale.fromSubtags(
    languageCode: 'zh',
    scriptCode: 'Hant',
  ),
};

Locale resolvedLocaleForLanguage(AppLanguage language, Locale systemLocale) {
  final explicit = localeForLanguage(language);
  if (explicit != null) return explicit;
  if (systemLocale.languageCode == 'zh') {
    return const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant');
  }
  return AppLocalizations.supportedLocales.firstWhere(
    (locale) => locale.languageCode == systemLocale.languageCode,
    orElse: () => const Locale('en'),
  );
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const {'ko', 'en', 'ja', 'zh'}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    '시스템 설정에 따름': 'Follow system settings',
    '언어': 'Language',
    '설정': 'Settings',
    '알림 설정': 'Notification Settings',
    '계정 설정': 'Account Settings',
    '알림': 'Notifications',
    '일정 알림, 아침 브리핑, D-day 알림':
        'Event reminders, morning briefing, and D-day alerts',
    '계정': 'Account',
    'Siri 작업 기록': 'Siri Activity',
    'Siri 작업 상세': 'Siri Action Details',
    '작업': 'Action',
    '상태': 'Status',
    '실행 시각': 'Executed at',
    '요약': 'Summary',
    '결과': 'Result',
    '시작': 'Start',
    '종료': 'End',
    '종일 일정': 'All-day event',
    '예': 'Yes',
    '아니요': 'No',
    '기록 전체 삭제': 'Clear all activity',
    'Siri 작업 기록 삭제': 'Clear Siri activity',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': 'Delete all saved Siri activity?',
    '성공': 'Success',
    '실패': 'Failed',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.':
        'Review Daily actions run by Siri and automations by date.',
    '날짜 선택': 'Choose date',
    '전체 날짜 보기': 'Show all dates',
    '기록된 Siri 작업이 없습니다.': 'No Siri activity recorded.',
    '오늘 일정 조회': "Today's events",
    '내일 일정 조회': "Tomorrow's events",
    '날짜별 일정 조회': 'Events by date',
    '다음 일정 조회': 'Next event',
    'D-day 조회': 'D-day events',
    '달력 열기': 'Open calendar',
    'Siri 작업': 'Siri action',
    '지금 듣는 중...': 'Listening...',
    '시그널 처리 중...': 'Processing Signal...',
    '다시 말씀해 주세요': 'Please try again',
    '필요한 정보를 이어서 말씀해 주세요.': 'Please continue with the missing information.',
    '음성 명령을 처리하지 못했습니다.': 'The voice command could not be processed.',
    '듣기 중지': 'Stop listening',
    '다시 듣기': 'Listen again',
    '음성 듣기가 중단되었습니다.': 'Listening was interrupted.',
    '이 명령을 실행할까요?': 'Run this command?',
    '인증 또는 작업이 취소되었습니다.': 'Authentication or the action was cancelled.',
    '기기 인증을 완료하지 못했습니다.': 'Device authentication could not be completed.',
    '작업을 취소했습니다.': 'The action was cancelled.',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.':
        'The event was saved, but notification or sync processing is pending.',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.':
        'The event was saved. Cloud sync will retry after an account is connected.',
    '실행 확인': 'Confirm action',
    '듣기 완료': 'Finish listening',
    '텍스트로 입력': 'Type instead',
    'Daily에 요청할 내용을 입력하세요.': 'Enter a request for Daily.',
    'Apple, Google, 동기화 및 계정 관리': 'Apple, Google, sync, and account management',
    '화면': 'Appearance',
    '테마': 'Theme',
    '자동': 'System',
    '화이트': 'Light',
    '다크': 'Dark',
    '달력': 'Calendar',
    '주 시작 요일': 'First day of week',
    '일': 'Sun',
    '월': 'Mon',
    '주 보기': 'Week',
    '월 보기': 'Month',
    '일 보기': 'Day',
    '음력 표시': 'Show lunar dates',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.':
        'Show lunar dates alongside dates in the month calendar.',
    '인접한 달 날짜 표시': 'Show adjacent month dates',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.':
        'Unavailable in vertical scrolling to keep month boundaries clear.',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.':
        'Show previous and next month dates in the first and last weeks.',
    '월간 이동 방식': 'Month navigation',
    '좌우 슬라이드': 'Swipe horizontally',
    '상하 스크롤': 'Scroll vertically',
    '기본 보기': 'Default view',
    '주간·일간 표시 방식': 'Week/day layout',
    '목록': 'List',
    '스케줄': 'Schedule',
    '종일 일정 표시': 'Show all-day events',
    '종일 일정 숨기기': 'Hide all-day events',
    '앱을 열었을 때 먼저 보여줄 달력 보기': 'Calendar view shown when the app opens',
    '주간': 'Week',
    '월간': 'Month',
    '일간': 'Day',
    '전체 UI 글자 크기': 'Interface text size',
    '기본': 'Default',
    '크게': 'Large',
    '더 크게': 'Larger',
    '개인정보': 'Privacy',
    '앱 잠금': 'App Lock',
    '앱을 다시 열 때 사용자를 확인합니다.': 'Verify the user when the app is reopened.',
    'PIN 없이 잠금': 'Lock without PIN',
    'PIN 잠금': 'PIN lock',
    '시스템 잠금 비밀번호': 'System authentication',
    '생체인식 잠금 해제': 'Biometric unlock',
    '분류': 'Categories',
    '분류 추가': 'Add category',
    'AI': 'AI',
    'AI 기능': 'AI features',
    '개발 중입니다.': 'In development.',
    'Gemini 사용': 'Use Gemini',
    '민감 문장 AI 차단': 'Block sensitive text from AI',
    '캘린더 데이터 옮기기': 'Import calendar data',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.':
        'Import from Apple Calendar or Google Calendar.',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.':
        'Import from Samsung Calendar or Google Calendar.',
    '건너뛰기': 'Skip',
    '이전': 'Back',
    '다음': 'Next',
    '일정을 한눈에': 'Your schedule at a glance',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.':
        'Focus quickly with month, week, and day views.',
    '기록하고 바로 알림 받기': 'Add events and get reminders',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.':
        'Add events naturally and receive reminders and morning briefings.',
    '중요한 날까지 이어서': 'Stay on track for important days',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        'Use D-day and categories, and continue across devices with Google Drive.',
    'Daily 시작하기': 'Get Started with Daily',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        'Connect Apple or Google, or start locally without an account.',
    'Apple로 계속': 'Continue with Apple',
    '로컬로 시작': 'Continue Locally',
    'Google 연결 중': 'Connecting Google',
    'Google로 계속': 'Continue with Google',
    '연결 취소': 'Cancel connection',
    '알림 권한 허용': 'Allow Notifications',
    '검색': 'Search',
    '필터': 'Filter',
    '오늘': 'Today',
    '빠른 보기': 'Quick View',
    '일정 추가': 'Add Event',
    '일정 수정': 'Edit Event',
    '저장': 'Save',
    '취소': 'Cancel',
    '삭제': 'Delete',
    '수정': 'Edit',
    '제목': 'Title',
    '시간': 'Time',
    '장소': 'Location',
    '메모': 'Notes',
    '종일': 'All-day',
    '반복': 'Repeat',
    '없음': 'None',
    '완료': 'Done',
    '지도 바로가기': 'Open in Maps',
    '월간 미니 캘린더': 'Mini Month Calendar',
    '오늘 일정': "Today's Events",
    '일정 없음': 'No events',
    '중요한 날짜': 'Important dates',
    'D-day 일정 없음': 'No D-day events',
    '일정 {count}개': '{count} events',
    'D-day {count}개': '{count} D-day events',
    '공휴일 {count}개': '{count} holidays',
    '검색 닫기': 'Close search',
    '현재 보기에서 검색': 'Search current view',
    'D-day 일정만 보기': 'Show only D-day events',
    '공휴일 표시': 'Show holidays',
    '분류 표시': 'Visible categories',
    '검색어 지우기': 'Clear search',
    'AI 입력 닫기': 'Close AI input',
    '일정을 입력하세요': 'Enter an event',
    '등록': 'Add',
    '이 일정으로 등록할까요?': 'Add this event?',
    '열기': 'Open',
    '추가 상세정보가 없습니다.': 'No additional details.',
    '주': 'week',
    '개월': 'month',
    '년': 'year',
    '번': 'time',
    '제목을 입력하세요.': 'Enter a title.',
    '시작일': 'Start date',
    '종료일': 'End date',
    '시작 시간': 'Start time',
    '종료 시간': 'End time',
    '알림 직접 입력': 'Custom reminder',
    '일정 알람': 'Event alarm',
    '종일 일정 알람 시각': 'All-day alarm time',
    'URL / 링크': 'URL / Link',
    '날씨': 'Weather',
    '예: 흐림': 'e.g. Cloudy',
    'D-day 표시': 'Show D-day',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': 'Show D-day in the calendar and event list.',
    '제목, 메모, 장소 검색': 'Search title, notes, or location',
    '검색 결과가 없습니다.': 'No search results.',
    'Apple 연동 해지': 'Disconnect Apple',
    'Google 연동 해지': 'Disconnect Google',
    'D-day 알림': 'D-day reminders',
    'Daily 계정': 'Daily Account',
    'Daily 버전': 'Daily Version',
    'Google Drive 동기화': 'Google Drive Sync',
    'Google Drive에서 복원': 'Restore from Google Drive',
    'Google 계정': 'Google Account',
    'Google 로그인 시 Daily 계정에 연결됩니다.':
        'Signing in with Google links it to your Daily account.',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        'Back up and restore events in this account’s Google Drive AppData.',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        'The Google session is unavailable. Reconnect to resume automatic sync.',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        'Google sign-in also requests access to Drive AppData.',
    '백업': 'Back Up',
    'Google 다시 연결': 'Reconnect Google',
    'Daily 계정 탈퇴': 'Delete Daily Account',
    '로컬 데이터 초기화': 'Reset Local Data',
    'Apple로 로그인됨': 'Signed in with Apple',
    'Apple 로그인': 'Apple Sign-In',
    'Daily 계정에 연결된 Apple 로그인입니다.':
        'This Apple sign-in is linked to your Daily account.',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.':
        'You can use Daily with Apple sign-in only.',
    'Apple 또는 Google 계정을 연결할 수 있습니다.':
        'You can link an Apple or Google account.',
    '{providers} 로그인 연결됨': '{providers} sign-in linked',
    '아직 동기화 기록이 없습니다.': 'No sync activity yet.',
    '백업 중': 'Backing up',
    '복원 중': 'Restoring',
    '동기화 중': 'Syncing',
    '다른 기기 변경 확인 중': 'Checking changes from other devices',
    '백업 완료': 'Backup complete',
    '복원 완료': 'Restore complete',
    '동기화 완료': 'Sync complete',
    '최신 상태': 'Up to date',
    '일부 백업 보류 · 먼저 복원 필요': 'Some changes are pending · restore first',
    '다른 기기 변경 확인 준비 중': 'Preparing to check changes from other devices',
    '동기화 완료 · 다른 기기 변경 복원':
        'Sync complete · restored changes from another device',
    'PIN 확인': 'Verify PIN',
    '계속': 'Continue',
    '기본 알림 직접 입력': 'Enter default reminder',
    '동기화 상태': 'Sync Status',
    '로그아웃': 'Sign Out',
    '아침 브리핑': 'Morning Briefing',
    '알림 테스트': 'Test Notification',
    '복원': 'Restore',
    '분류 삭제': 'Delete Category',
    '분류 수정': 'Edit Category',
    '사용자 지정 색상': 'Custom Color',
    '시간 선택': 'Choose Time',
    '시간 표시 방식': 'Time Format',
    '시스템 알림 설정 열기': 'Open System Notification Settings',
    '백업 삭제 후 해제': 'Delete backup and disconnect',
    '백업 없이 로그아웃': 'Sign out without backup',
    '백업을 완료하지 못했습니다': 'Backup Could Not Be Completed',
    '버그 제보': 'Report a Bug',
    '보내기': 'Send',
    '연동 해지': 'Disconnect',
    '연동만 해제': 'Disconnect only',
    '저장 내용 초기화': 'Delete saved data',
    '적용': 'Apply',
    '직접 입력': 'Custom',
    '잠금 방식 변경': 'Change Lock Method',
    '잠금 방식 선택': 'Choose Lock Method',
    '한 자리 지우기': 'Delete one digit',
    '앱 정보': 'App Information',
    '일정이 시작됩니다.': 'The event is starting.',
    '일정 시작 {time}입니다.': 'The event starts {time}.',
    'D-day 일정 알림입니다.': 'This is a D-day event reminder.',
    '오늘의 일정': "Today's Events",
    'Daily 알림 테스트': 'Daily Notification Test',
    '이 알림이 보이면 Daily의 알림 표시 권한은 정상입니다.':
        'If you can see this, Daily notification permission is working.',
    '오늘 등록된 일정이 없습니다.': 'There are no events today.',
    ' 외 {count}개 더 있습니다.': ' and {count} more.',
    '정시': 'At time of event',
    '{count}분 전': '{count} minutes before',
    '{count}일 전': '{count} days before',
    '{count}시간 전': '{count} hours before',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.':
        "Shows today's events at the selected time each day.",
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.':
        'Open the GitHub report form in your default browser.',
    'GitHub Repository를 열 수 없습니다.': 'Could not open the GitHub repository.',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.':
        'Could not open the bug report page. Please try again later.',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': 'Enter your PIN to unlock the app.',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.':
        'System authentication is unavailable on this device.',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?':
        'Continue changing from the current lock-without-PIN method?',
    '기본 일정 알림': 'Default event reminders',
    '몇 분 전에 알릴까요?': 'How many minutes before?',
    '종일 일정 알림 시간': 'All-day reminder time',
    '종일 일정의 알림 기준 시간': 'Default reminder time for all-day events',
    '아침 브리핑 시간': 'Morning briefing time',
    '브리핑을 받을 시간': 'Time to receive the briefing',
    'D-day 알림 직접 입력': 'Custom D-day reminder',
    'D-day 기준 일수. 예: -7, 0': 'Days relative to D-day, e.g. -7, 0',
    '앱 잠금 PIN 설정': 'Set App Lock PIN',
    '잠금 방식': 'Lock method',
    '버전 {version} · 더블 클릭하여 Github 확인하기':
        'Version {version} · Double-click to view GitHub',
    '이름': 'Name',
    '색상': 'Color',
    '"{category}" 분류를 삭제할까요?': 'Delete the “{category}” category?',
    '닫기': 'Close',
    '검색/필터': 'Search / Filter',
    '반복 종료': 'Repeat ends',
    '종료 없음': 'Never',
    '날짜까지': 'On date',
    '횟수만큼': 'After occurrences',
    '반복 간격': 'Repeat interval',
    '몇 {unit}마다 반복할까요?': 'Repeat every how many {unit}?',
    '반복 횟수': 'Number of repeats',
    '몇 회 반복할까요?': 'How many times should it repeat?',
    '제목을 입력해야 일정을 저장할 수 있습니다.': 'Enter a title before saving the event.',
    '종료일은 시작일과 같거나 이후여야 합니다.':
        'The end date must be on or after the start date.',
    '종료 시간은 시작 시간보다 늦어야 합니다.':
        'The end time must be later than the start time.',
    '반복 간격은 1 이상이어야 합니다.': 'The repeat interval must be at least 1.',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.':
        'Repeating alarms will be available with routines later.',
    '알람 지원 상태를 확인하고 있습니다.': 'Checking alarm support.',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.':
        'Event alarms are unavailable on this operating system.',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.':
        'Allow Daily alarm access in system settings.',
    '0 이상의 숫자를 입력하세요.': 'Enter a number of 0 or greater.',
    '{count} 이상의 숫자를 입력하세요.': 'Enter a number of {count} or greater.',
    '반복 일정 수정': 'Edit Repeating Event',
    '반복 일정 삭제': 'Delete Repeating Event',
    '일정 삭제': 'Delete Event',
    '"{title}" 일정을 삭제할까요?': 'Delete “{title}”?',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?':
        'Which occurrences should this {action} apply to?',
    '이 일정만': 'Only This Event',
    '이후 일정': 'This and Future Events',
    '전체 반복': 'All Events',
    '일정을 옮기는 중': 'Importing events',
    '{count}개 캘린더 가져오기': 'Import {count} calendars',
    '가져올 수 있는 {provider}가 없습니다.': 'No {provider} calendars are available.',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        'Import complete: {imported} added, {skipped} duplicates skipped, {failed} failed',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.':
        'Check calendar permission or connection status.',
    '가져올 캘린더를 선택해 주세요.': 'Select a calendar to import.',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.':
        'Allow Daily full calendar access in Settings.',
    '캘린더 접근이 허용되지 않았습니다.': 'Calendar access was not granted.',
    'Google 계정 로그인이 필요합니다.': 'Sign in to a Google account first.',
    'Google Calendar 응답 형식이 올바르지 않습니다.':
        'Google Calendar returned an invalid response.',
    '{title} 불러오기': 'Load {title}',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'Content is hidden while the app is locked.',
    '잠금 상태입니다.': 'Locked',
    'PIN 입력': 'Enter PIN',
    '비밀번호를 통해 잠금해제': 'Unlock with PIN',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.':
        'Verify with Face ID, Touch ID, or the device password.',
    '시스템 잠금으로 해제': 'Unlock with System Authentication',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.':
        'Continue entering the PIN, or clear it and try again.',
    'PIN이 일치하지 않습니다.': 'The PIN does not match.',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': 'Authentication is required to unlock Daily.',
    '시스템 인증을 완료하지 못했습니다.': 'System authentication was not completed.',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        'Unlock Daily PIN lock with Touch ID or Apple Watch.',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': 'Unlock Daily PIN lock with biometrics.',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.':
        'Biometric authentication was not completed. Enter your PIN.',
    '일정이 없습니다.': 'No events.',
    '시작 시각 · 중지 또는 10분 후 다시 알림': 'Start time · Stop or snooze for 10 minutes',
    '{time} · 중지 또는 10분 후 다시 알림': '{time} · Stop or snooze for 10 minutes',
    'Apple 로그인 창을 여는 중입니다.': 'Opening Apple sign-in.',
    'Apple 로그인이 취소되었습니다.': 'Apple sign-in was canceled.',
    'Apple 로그인이 완료되었습니다.': 'Apple sign-in completed.',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Apple sign-in completed. The linked Google Drive sync was restored.',
    'Apple 연동을 해지했습니다.': 'Apple was disconnected.',
    'Google 로그인 창을 여는 중입니다.': 'Opening Google sign-in.',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.':
        'Google Drive connection was canceled. You can connect again.',
    '알림 권한 요청을 여는 중입니다.': 'Opening the notification permission request.',
    '알림 권한 설정을 확인했습니다.': 'Notification permission settings checked.',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.':
        'Hide content while away and unlock automatically when you return.',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        'Lock with a Daily PIN and optionally use biometrics.',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.':
        'Authenticate with Face ID, Touch ID, or the device password.',
    '알림 상태 확인 중입니다.': 'Checking notification status.',
    '테스트 알림을 보냈습니다. {summary}': 'Test notification sent. {summary}',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        'Could not open notification settings. Allow Daily notifications in system settings.',
    'Gemini API 키': 'Gemini API Key',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        'On Android, enable notifications in Settings > Apps > Daily > Notifications.',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.':
        'All-day events use the all-day reminder time from Settings.',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        'Requests macOS notification permission and sends a system notification at the start time.',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.':
        'Requests alarm permission and replaces the start-time notification with an alarm.',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        'Sends a macOS system notification with sound and snooze at the selected time.',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        'Sends a macOS system notification with sound and snooze at the start time.',
    '선택한 시각에 시스템 알람이 울립니다.': 'A system alarm sounds at the selected time.',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.':
        'Replaces the start-time notification with a system alarm.',
    'Google Drive 연결이 완료되었습니다.': 'Google Drive connected.',
    'Google Drive 복원 완료': 'Google Drive restore completed',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        'The request could not be completed. Try again shortly.',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.':
        'Check your network connection and try again.',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.':
        'The Google Drive connection expired. Connect again.',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Drive permission is insufficient. Reconnect and approve access.',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        'Too many Google Drive requests. Try again shortly.',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.':
        'Google Drive is temporarily unstable. Try again shortly.',
    'PIN 없음': 'No PIN',
    '시스템': 'System',
    '즉시 알림을 보내고 예약 상태를 확인합니다.':
        'Send a notification now and check scheduled status.',
    'PIN은 4자리 이상이어야 합니다.': 'PIN must contain at least 4 digits.',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PINs do not match. Try again.',
    '마지막 성공: {time}': 'Last success: {time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.':
        'Do not add reminders automatically to new events.',
    'Apple 캘린더': 'Apple Calendar',
    'Samsung 캘린더': 'Samsung Calendar',
    'Google 캘린더': 'Google Calendar',
    '공휴일': 'Holidays',
    '신정': "New Year's Day",
    '삼일절': 'March 1st Movement Day',
    '노동절': 'Labor Day',
    '어린이날': "Children's Day",
    '현충일': 'Memorial Day',
    '제헌절': 'Constitution Day',
    '광복절': 'Liberation Day',
    '개천절': 'National Foundation Day',
    '한글날': 'Hangeul Day',
    '기독탄신일': 'Christmas Day',
    '설날 연휴': 'Seollal Holiday',
    '설날': 'Seollal',
    '부처님 오신 날': "Buddha's Birthday",
    '추석 연휴': 'Chuseok Holiday',
    '추석': 'Chuseok',
    '대체공휴일': 'Substitute Holiday',
    '반복 없음': 'Does not repeat',
    '매일': 'Daily',
    '매주': 'Weekly',
    '매월': 'Monthly',
    '매년': 'Yearly',
    '반복 종료일': 'Repeat end date',
    '{count}회': '{count} times',
    '{count}일마다': 'Every {count} day(s)',
    '{count}주마다': 'Every {count} week(s)',
    '{count}개월마다': 'Every {count} month(s)',
    '{count}년마다': 'Every {count} year(s)',
    '{count}번마다': 'Every {count} time(s)',
  },
  'ja': {
    '시스템 설정에 따름': 'システム設定に従う',
    '언어': '言語',
    '설정': '設定',
    '알림 설정': '通知設定',
    '계정 설정': 'アカウント設定',
    '알림': '通知',
    '계정': 'アカウント',
    'Siri 작업 기록': 'Siriアクティビティ',
    'Siri 작업 상세': 'Siri操作の詳細',
    '작업': '操作',
    '상태': '状態',
    '실행 시각': '実行日時',
    '요약': '概要',
    '결과': '結果',
    '시작': '開始',
    '종료': '終了',
    '종일 일정': '終日予定',
    '예': 'はい',
    '아니요': 'いいえ',
    '기록 전체 삭제': 'すべての履歴を削除',
    'Siri 작업 기록 삭제': 'Siriアクティビティを削除',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': '保存されたSiriアクティビティをすべて削除しますか？',
    '성공': '成功',
    '실패': '失敗',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.':
        'Siriとオートメーションで実行したDailyの操作を日付別に確認します。',
    '날짜 선택': '日付を選択',
    '전체 날짜 보기': 'すべての日付を表示',
    '기록된 Siri 작업이 없습니다.': 'Siriの操作履歴はありません。',
    '오늘 일정 조회': '今日の予定',
    '내일 일정 조회': '明日の予定',
    '날짜별 일정 조회': '日付別の予定',
    '다음 일정 조회': '次の予定',
    'D-day 조회': 'D-day予定',
    '달력 열기': 'カレンダーを開く',
    'Siri 작업': 'Siri操作',
    '지금 듣는 중...': '聞き取り中...',
    '시그널 처리 중...': 'シグナルを処理中...',
    '다시 말씀해 주세요': 'もう一度お話しください',
    '필요한 정보를 이어서 말씀해 주세요.': '不足している情報を続けてお話しください。',
    '음성 명령을 처리하지 못했습니다.': '音声コマンドを処理できませんでした。',
    '듣기 중지': '聞き取りを停止',
    '다시 듣기': 'もう一度聞く',
    '음성 듣기가 중단되었습니다.': '聞き取りが中断されました。',
    '이 명령을 실행할까요?': 'このコマンドを実行しますか？',
    '인증 또는 작업이 취소되었습니다.': '認証または操作がキャンセルされました。',
    '기기 인증을 완료하지 못했습니다.': 'デバイス認証を完了できませんでした。',
    '작업을 취소했습니다.': '操作をキャンセルしました。',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.':
        '予定は保存されましたが、通知または同期処理は保留中です。',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.':
        '予定は保存されました。クラウド同期はアカウント接続後に再試行されます。',
    '실행 확인': '実行の確認',
    '듣기 완료': '聞き取りを完了',
    '텍스트로 입력': 'テキストで入力',
    'Daily에 요청할 내용을 입력하세요.': 'Dailyへのリクエストを入力してください。',
    '화면': '画面',
    '테마': 'テーマ',
    '자동': '自動',
    '화이트': 'ライト',
    '다크': 'ダーク',
    '달력': 'カレンダー',
    '주 시작 요일': '週の開始曜日',
    '일': '日',
    '월': '月',
    '주 보기': '週',
    '월 보기': '月',
    '일 보기': '日',
    '음력 표시': '旧暦を表示',
    '인접한 달 날짜 표시': '隣接月の日付を表示',
    '월간 이동 방식': '月表示の移動方法',
    '좌우 슬라이드': '左右スワイプ',
    '상하 스크롤': '上下スクロール',
    '기본 보기': 'デフォルト表示',
    '주간·일간 표시 방식': '週・日表示方式',
    '목록': 'リスト',
    '스케줄': 'スケジュール',
    '종일 일정 표시': '終日予定を表示',
    '종일 일정 숨기기': '終日予定を非表示',
    '주간': '週',
    '월간': '月',
    '일간': '日',
    '전체 UI 글자 크기': 'UI文字サイズ',
    '기본': '標準',
    '크게': '大',
    '더 크게': '特大',
    '개인정보': 'プライバシー',
    '앱 잠금': 'アプリロック',
    'PIN 없이 잠금': 'PINなしロック',
    'PIN 잠금': 'PINロック',
    '시스템 잠금 비밀번호': 'システム認証',
    '생체인식 잠금 해제': '生体認証でロック解除',
    '분류': 'カテゴリ',
    '분류 추가': 'カテゴリを追加',
    'AI 기능': 'AI機能',
    '개발 중입니다.': '開発中です。',
    '캘린더 데이터 옮기기': 'カレンダーデータを読み込む',
    '건너뛰기': 'スキップ',
    '이전': '戻る',
    '다음': '次へ',
    '일정을 한눈에': '予定をひと目で',
    '기록하고 바로 알림 받기': '記録してすぐ通知',
    '중요한 날까지 이어서': '大切な日までしっかり管理',
    'Daily 시작하기': 'Dailyを始める',
    'Apple로 계속': 'Appleで続ける',
    '로컬로 시작': 'ローカルで始める',
    'Google 연결 중': 'Googleに接続中',
    'Google로 계속': 'Googleで続ける',
    '연결 취소': '接続をキャンセル',
    '알림 권한 허용': '通知を許可',
    '검색': '検索',
    '필터': 'フィルタ',
    '오늘': '今日',
    '빠른 보기': 'クイック表示',
    '일정 추가': '予定を追加',
    '일정 수정': '予定を編集',
    '저장': '保存',
    '취소': 'キャンセル',
    '삭제': '削除',
    '수정': '編集',
    '제목': 'タイトル',
    '시간': '時刻',
    '장소': '場所',
    '메모': 'メモ',
    '종일': '終日',
    '반복': '繰り返し',
    '없음': 'なし',
    '완료': '完了',
    '지도 바로가기': '地図で開く',
    '월간 미니 캘린더': '月間ミニカレンダー',
    '오늘 일정': '今日の予定',
    '일정 없음': '予定なし',
    '중요한 날짜': '重要な日',
    'D-day 일정 없음': 'D-day予定なし',
    '일정 {count}개': '予定{count}件',
    'D-day {count}개': 'D-day {count}件',
    '공휴일 {count}개': '祝日{count}件',
    '검색 닫기': '検索を閉じる',
    '현재 보기에서 검색': '現在の表示を検索',
    'D-day 일정만 보기': 'D-day予定のみ表示',
    '공휴일 표시': '祝日を表示',
    '분류 표시': '表示するカテゴリ',
    '검색어 지우기': '検索語を消去',
    'AI 입력 닫기': 'AI入力を閉じる',
    '일정을 입력하세요': '予定を入力してください',
    '등록': '登録',
    '이 일정으로 등록할까요?': 'この予定を登録しますか？',
    '열기': '開く',
    '추가 상세정보가 없습니다.': '追加情報はありません。',
    '주': '週',
    '개월': 'か月',
    '년': '年',
    '번': '回',
    '제목을 입력하세요.': 'タイトルを入力してください。',
    '시작일': '開始日',
    '종료일': '終了日',
    '시작 시간': '開始時刻',
    '종료 시간': '終了時刻',
    '알림 직접 입력': '通知を直接入力',
    '일정 알람': '予定アラーム',
    '종일 일정 알람 시각': '終日予定のアラーム時刻',
    'URL / 링크': 'URL / リンク',
    '날씨': '天気',
    '예: 흐림': '例：曇り',
    'D-day 표시': 'D-dayを表示',
    '제목, 메모, 장소 검색': 'タイトル、メモ、場所を検索',
    '검색 결과가 없습니다.': '検索結果がありません。',
    'Apple 연동 해지': 'Apple連携を解除',
    'Google 연동 해지': 'Google連携を解除',
    'D-day 알림': 'D-day通知',
    'Daily 계정': 'Dailyアカウント',
    'Daily 버전': 'Dailyバージョン',
    'Google Drive 동기화': 'Google Drive同期',
    'Google Drive에서 복원': 'Google Driveから復元',
    'Google 계정': 'Googleアカウント',
    'Google 로그인 시 Daily 계정에 연결됩니다.': 'GoogleでログインするとDailyアカウントに連携されます。',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        'このアカウントのGoogle Drive AppDataに予定をバックアップし、復元します。',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        'Google認証セッションがありません。再接続すると自動同期が再開します。',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        'Googleログイン時にDrive AppDataへのアクセスも許可します。',
    '백업': 'バックアップ',
    'Google 다시 연결': 'Googleに再接続',
    'Daily 계정 탈퇴': 'Dailyアカウントを削除',
    '로컬 데이터 초기화': 'ローカルデータを初期化',
    'Apple로 로그인됨': 'Appleでログイン済み',
    'Apple 로그인': 'Appleログイン',
    'Daily 계정에 연결된 Apple 로그인입니다.': 'Dailyアカウントに連携されたAppleログインです。',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.': 'AppleログインだけでDailyを利用できます。',
    'Apple 또는 Google 계정을 연결할 수 있습니다.': 'AppleまたはGoogleアカウントを連携できます。',
    '{providers} 로그인 연결됨': '{providers}ログイン連携済み',
    '아직 동기화 기록이 없습니다.': '同期履歴はまだありません。',
    '백업 중': 'バックアップ中',
    '복원 중': '復元中',
    '동기화 중': '同期中',
    '다른 기기 변경 확인 중': 'ほかのデバイスの変更を確認中',
    '백업 완료': 'バックアップ完了',
    '복원 완료': '復元完了',
    '동기화 완료': '同期完了',
    '최신 상태': '最新の状態',
    '일부 백업 보류 · 먼저 복원 필요': '一部保留中・先に復元が必要',
    '다른 기기 변경 확인 준비 중': 'ほかのデバイスの変更確認を準備中',
    '동기화 완료 · 다른 기기 변경 복원': '同期完了・ほかのデバイスの変更を復元',
    'PIN 확인': 'PIN確認',
    '계속': '続ける',
    '기본 알림 직접 입력': 'デフォルト通知を入力',
    '동기화 상태': '同期状態',
    '로그아웃': 'ログアウト',
    '아침 브리핑': '朝のブリーフィング',
    '알림 테스트': '通知テスト',
    '복원': '復元',
    '분류 삭제': 'カテゴリを削除',
    '분류 수정': 'カテゴリを編集',
    '사용자 지정 색상': 'カスタムカラー',
    '시간 선택': '時刻を選択',
    '시간 표시 방식': '時刻表示形式',
    '시스템 알림 설정 열기': 'システム通知設定を開く',
    '백업 삭제 후 해제': 'バックアップを削除して解除',
    '백업 없이 로그아웃': 'バックアップせずログアウト',
    '백업을 완료하지 못했습니다': 'バックアップを完了できませんでした',
    '버그 제보': '不具合を報告',
    '보내기': '送信',
    '연동 해지': '連携解除',
    '연동만 해제': '連携のみ解除',
    '저장 내용 초기화': '保存内容を削除',
    '적용': '適用',
    '직접 입력': 'カスタム',
    '잠금 방식 변경': 'ロック方式を変更',
    '잠금 방식 선택': 'ロック方式を選択',
    '한 자리 지우기': '1桁削除',
    '앱 정보': 'アプリ情報',
    '일정이 시작됩니다.': '予定が始まります。',
    '일정 시작 {time}입니다.': '予定開始の{time}です。',
    'D-day 일정 알림입니다.': 'D-day予定のお知らせです。',
    '오늘의 일정': '今日の予定',
    'Daily 알림 테스트': 'Daily通知テスト',
    '이 알림이 보이면 Daily의 알림 표시 권한은 정상입니다.': 'この通知が表示されれば、Dailyの通知権限は正常です。',
    '오늘 등록된 일정이 없습니다.': '今日の予定はありません。',
    ' 외 {count}개 더 있습니다.': '、ほか{count}件',
    '정시': '予定時刻',
    '{count}분 전': '{count}分前',
    '{count}일 전': '{count}日前',
    '{count}시간 전': '{count}時間前',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': 'アプリのロック解除用PINを入力してください。',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.': 'このデバイスではシステム認証を利用できません。',
    '기본 일정 알림': '予定のデフォルト通知',
    '몇 분 전에 알릴까요?': '何分前に通知しますか？',
    '종일 일정 알림 시간': '終日予定の通知時刻',
    '종일 일정의 알림 기준 시간': '終日予定の基準通知時刻',
    '아침 브리핑 시간': '朝のブリーフィング時刻',
    '브리핑을 받을 시간': 'ブリーフィングを受け取る時刻',
    'D-day 알림 직접 입력': 'D-day通知を直接入力',
    'D-day 기준 일수. 예: -7, 0': 'D-day基準の日数。例：-7、0',
    '앱 잠금 PIN 설정': 'アプリロックPINを設定',
    '잠금 방식': 'ロック方式',
    '버전 {version} · 더블 클릭하여 Github 확인하기': 'バージョン{version}・ダブルクリックでGitHubを表示',
    '이름': '名前',
    '색상': '色',
    '"{category}" 분류를 삭제할까요?': '「{category}」カテゴリを削除しますか？',
    '닫기': '閉じる',
    '검색/필터': '検索／フィルタ',
    '반복 종료': '繰り返し終了',
    '종료 없음': '終了なし',
    '날짜까지': '指定日まで',
    '횟수만큼': '回数を指定',
    '반복 간격': '繰り返し間隔',
    '몇 {unit}마다 반복할까요?': '何{unit}ごとに繰り返しますか？',
    '반복 횟수': '繰り返し回数',
    '몇 회 반복할까요?': '何回繰り返しますか？',
    '제목을 입력해야 일정을 저장할 수 있습니다.': '予定を保存するにはタイトルを入力してください。',
    '종료일은 시작일과 같거나 이후여야 합니다.': '終了日は開始日以降にしてください。',
    '종료 시간은 시작 시간보다 늦어야 합니다.': '終了時刻は開始時刻より後にしてください。',
    '반복 간격은 1 이상이어야 합니다.': '繰り返し間隔は1以上にしてください。',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.': '繰り返しアラームは今後ルーティン機能で利用できます。',
    '알람 지원 상태를 확인하고 있습니다.': 'アラーム対応状況を確認しています。',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.': 'このOSでは予定アラームを利用できません。',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.': 'システム設定でDailyのアラーム権限を許可してください。',
    '반복 일정 수정': '繰り返し予定を編集',
    '반복 일정 삭제': '繰り返し予定を削除',
    '일정 삭제': '予定を削除',
    '"{title}" 일정을 삭제할까요?': '「{title}」を削除しますか？',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?': 'この繰り返し予定のどの範囲に{action}を適用しますか？',
    '이 일정만': 'この予定のみ',
    '이후 일정': 'これ以降の予定',
    '전체 반복': 'すべての予定',
    '일정을 옮기는 중': '予定を読み込み中',
    '{count}개 캘린더 가져오기': '{count}個のカレンダーを読み込む',
    '가져올 수 있는 {provider}가 없습니다.': '読み込める{provider}カレンダーがありません。',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        '読み込み完了：{imported}件追加、{skipped}件の重複を除外、{failed}件失敗',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.': 'カレンダーの権限または接続状態を確認してください。',
    '가져올 캘린더를 선택해 주세요.': '読み込むカレンダーを選択してください。',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.': '設定でDailyにカレンダーへのフルアクセスを許可してください。',
    '캘린더 접근이 허용되지 않았습니다.': 'カレンダーへのアクセスが許可されませんでした。',
    'Google 계정 로그인이 필요합니다.': 'Googleアカウントへのログインが必要です。',
    'Google Calendar 응답 형식이 올바르지 않습니다.': 'Google Calendarから無効な応答が返されました。',
    '{title} 불러오기': '{title}を読み込む',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'ロック中は画面を表示できません。',
    '잠금 상태입니다.': 'ロック中',
    'PIN 입력': 'PINを入力',
    '비밀번호를 통해 잠금해제': 'PINでロック解除',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.':
        'Face ID、Touch ID、または端末のパスワードで確認します。',
    '시스템 잠금으로 해제': 'システム認証で解除',
    'PIN이 일치하지 않습니다.': 'PINが一致しません。',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': 'Dailyのロック解除には認証が必要です。',
    '시스템 인증을 완료하지 못했습니다.': 'システム認証を完了できませんでした。',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.': '生体認証を完了できませんでした。PINを入力してください。',
    '일정이 없습니다.': '予定がありません。',
    '시작 시각 · 중지 또는 10분 후 다시 알림': '開始時刻・停止または10分後に再通知',
    '{time} · 중지 또는 10분 후 다시 알림': '{time}・停止または10分後に再通知',
    'Apple 로그인 창을 여는 중입니다.': 'Appleサインインを開いています。',
    'Apple 로그인이 취소되었습니다.': 'Appleサインインがキャンセルされました。',
    'Apple 로그인이 완료되었습니다.': 'Appleサインインが完了しました。',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Appleサインインが完了し、連携済みのGoogle Drive同期を復元しました。',
    'Apple 연동을 해지했습니다.': 'Apple連携を解除しました。',
    'Google 로그인 창을 여는 중입니다.': 'Googleログインを開いています。',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.':
        'Google Drive接続がキャンセルされました。再接続できます。',
    '알림 권한 요청을 여는 중입니다.': '通知権限リクエストを開いています。',
    '알림 권한 설정을 확인했습니다.': '通知権限設定を確認しました。',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.': 'アプリを離れている間だけ画面を隠し、戻ると自動解除します。',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        'Daily専用PINでロックし、生体認証も任意で利用できます。',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.':
        'Face ID、Touch ID、または端末のパスワードで認証します。',
    '알림 상태 확인 중입니다.': '通知状態を確認しています。',
    '테스트 알림을 보냈습니다. {summary}': 'テスト通知を送信しました。{summary}',
    '일정 알림, 아침 브리핑, D-day 알림': '予定通知、朝のブリーフィング、D-day通知',
    'Apple, Google, 동기화 및 계정 관리': 'Apple、Google、同期、アカウント管理',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.': '月間カレンダーの各日に旧暦の日付も表示します。',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.': '月の境界を明確にするため、上下スクロールでは利用できません。',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.': '月間カレンダーの最初と最後の週に前後の月を表示します。',
    '앱을 열었을 때 먼저 보여줄 달력 보기': 'アプリ起動時に最初に表示するカレンダー',
    '앱을 다시 열 때 사용자를 확인합니다.': 'アプリを再度開くときにユーザーを確認します。',
    'AI': 'AI',
    'Gemini 사용': 'Geminiを使用',
    '민감 문장 AI 차단': '機密性の高い文章をAIから除外',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.': 'AppleカレンダーまたはGoogleカレンダーから読み込みます。',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.': 'SamsungカレンダーまたはGoogleカレンダーから読み込みます。',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.': '月・週・日表示で必要な予定にすぐ集中できます。',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.': '自然に予定を記録し、予定通知と朝のブリーフィングを受け取れます。',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        'D-dayとカテゴリを活用し、Google Driveで複数端末から続けて利用できます。',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        'AppleまたはGoogleを連携するか、アカウントなしでローカル利用を開始できます。',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': 'カレンダーと予定一覧にD-dayを表示します。',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.': '毎日指定した時刻に今日の予定をお知らせします。',
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.': '既定のブラウザでGitHubの報告フォームを開きます。',
    'GitHub Repository를 열 수 없습니다.': 'GitHubリポジトリを開けません。',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.': '不具合報告ページを開けません。しばらくしてから再試行してください。',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?': '現在のPINなしロックから変更を続けますか？',
    '0 이상의 숫자를 입력하세요.': '0以上の数値を入力してください。',
    '{count} 이상의 숫자를 입력하세요.': '{count}以上の数値を入力してください。',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.': 'PINの入力を続けるか、消去して再入力してください。',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        'Touch IDまたはApple WatchでDailyのPINロックを解除します。',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': '生体認証でDailyのPINロックを解除します。',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        '通知設定を開けません。OS設定でDailyの通知を許可してください。',
    'Gemini API 키': 'Gemini APIキー',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        'Androidでは「設定 > アプリ > Daily > 通知」で通知を許可してください。',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.': '終日予定は設定の終日通知時刻を基準に予約されます。',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        'macOSの通知権限を要求し、開始時刻にシステム通知を送信します。',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.': 'アラーム権限を要求し、開始時刻の通知をアラームに置き換えます。',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '選択した時刻に音と再通知付きのmacOSシステム通知を送信します。',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '開始時刻に音と再通知付きのmacOSシステム通知を送信します。',
    '선택한 시각에 시스템 알람이 울립니다.': '選択した時刻にシステムアラームが鳴ります。',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.': '開始時刻の通知をシステムアラームに置き換えます。',
    'Google Drive 연결이 완료되었습니다.': 'Google Driveに接続しました。',
    'Google Drive 복원 완료': 'Google Driveからの復元が完了しました',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.': 'リクエストを完了できませんでした。しばらくしてから再試行してください。',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.': 'ネットワーク接続を確認して再試行してください。',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.':
        'Google Drive接続の有効期限が切れました。再接続してください。',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Driveの権限が不足しています。再接続して権限を許可してください。',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        'Google Driveへのリクエストが多すぎます。しばらくしてから再試行してください。',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.':
        'Google Driveの応答が不安定です。しばらくしてから再試行してください。',
    'PIN 없음': 'PINなし',
    '시스템': 'システム',
    '즉시 알림을 보내고 예약 상태를 확인합니다.': '通知をすぐに送信し、予約状態を確認します。',
    'PIN은 4자리 이상이어야 합니다.': 'PINは4桁以上にしてください。',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PINが一致しません。再入力してください。',
    '마지막 성공: {time}': '最終成功：{time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.': '新しい予定に通知を自動追加しません。',
    'Apple 캘린더': 'Appleカレンダー',
    'Samsung 캘린더': 'Samsungカレンダー',
    'Google 캘린더': 'Googleカレンダー',
    '공휴일': '祝日',
    '신정': '元日',
    '삼일절': '三一節',
    '노동절': '労働節',
    '어린이날': 'こどもの日',
    '현충일': '顕忠日',
    '제헌절': '制憲節',
    '광복절': '光復節',
    '개천절': '開天節',
    '한글날': 'ハングルの日',
    '기독탄신일': 'クリスマス',
    '설날 연휴': '旧正月連休',
    '설날': '旧正月',
    '부처님 오신 날': '釈迦誕生日',
    '추석 연휴': '秋夕連休',
    '추석': '秋夕',
    '대체공휴일': '振替休日',
    '반복 없음': '繰り返さない',
    '매일': '毎日',
    '매주': '毎週',
    '매월': '毎月',
    '매년': '毎年',
    '반복 종료일': '繰り返し終了日',
    '{count}회': '{count}回',
    '{count}일마다': '{count}日ごと',
    '{count}주마다': '{count}週ごと',
    '{count}개월마다': '{count}か月ごと',
    '{count}년마다': '{count}年ごと',
    '{count}번마다': '{count}回ごと',
  },
  'zh_Hant': {
    '시스템 설정에 따름': '依照系統設定',
    '언어': '語言',
    '설정': '設定',
    '알림 설정': '通知設定',
    '계정 설정': '帳號設定',
    '알림': '通知',
    '계정': '帳號',
    'Siri 작업 기록': 'Siri 操作記錄',
    'Siri 작업 상세': 'Siri 操作詳細',
    '작업': '操作',
    '상태': '狀態',
    '실행 시각': '執行時間',
    '요약': '摘要',
    '결과': '結果',
    '시작': '開始',
    '종료': '結束',
    '종일 일정': '全天行程',
    '예': '是',
    '아니요': '否',
    '기록 전체 삭제': '清除所有記錄',
    'Siri 작업 기록 삭제': '刪除 Siri 操作記錄',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': '要刪除所有已儲存的 Siri 操作記錄嗎？',
    '성공': '成功',
    '실패': '失敗',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.': '依日期查看由 Siri 與自動化執行的 Daily 操作。',
    '날짜 선택': '選擇日期',
    '전체 날짜 보기': '顯示所有日期',
    '기록된 Siri 작업이 없습니다.': '尚無 Siri 操作記錄。',
    '오늘 일정 조회': '今日行程',
    '내일 일정 조회': '明日行程',
    '날짜별 일정 조회': '依日期查看行程',
    '다음 일정 조회': '下一個行程',
    'D-day 조회': 'D-day 行程',
    '달력 열기': '開啟行事曆',
    'Siri 작업': 'Siri 操作',
    '지금 듣는 중...': '正在聆聽...',
    '시그널 처리 중...': '正在處理 Signal...',
    '다시 말씀해 주세요': '請再說一次',
    '필요한 정보를 이어서 말씀해 주세요.': '請繼續提供缺少的資訊。',
    '음성 명령을 처리하지 못했습니다.': '無法處理語音指令。',
    '듣기 중지': '停止聆聽',
    '다시 듣기': '再次聆聽',
    '음성 듣기가 중단되었습니다.': '語音聆聽已中斷。',
    '이 명령을 실행할까요?': '要執行這個指令嗎？',
    '인증 또는 작업이 취소되었습니다.': '驗證或操作已取消。',
    '기기 인증을 완료하지 못했습니다.': '無法完成裝置驗證。',
    '작업을 취소했습니다.': '操作已取消。',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.':
        '行程已儲存，但通知或同步處理仍在等待中。',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.':
        '行程已儲存。連結帳號後將重新嘗試雲端同步。',
    '실행 확인': '確認執行',
    '듣기 완료': '完成聆聽',
    '텍스트로 입력': '改用文字輸入',
    'Daily에 요청할 내용을 입력하세요.': '輸入要交給 Daily 的要求。',
    '화면': '顯示',
    '테마': '主題',
    '자동': '自動',
    '화이트': '淺色',
    '다크': '深色',
    '달력': '行事曆',
    '주 시작 요일': '每週起始日',
    '일': '日',
    '월': '一',
    '주 보기': '週',
    '월 보기': '月',
    '일 보기': '日',
    '음력 표시': '顯示農曆',
    '인접한 달 날짜 표시': '顯示相鄰月份日期',
    '월간 이동 방식': '月份導覽方式',
    '좌우 슬라이드': '左右滑動',
    '상하 스크롤': '上下捲動',
    '기본 보기': '預設檢視',
    '주간·일간 표시 방식': '週／日顯示方式',
    '목록': '清單',
    '스케줄': '時間表',
    '종일 일정 표시': '顯示全日行程',
    '종일 일정 숨기기': '隱藏全日行程',
    '주간': '週',
    '월간': '月',
    '일간': '日',
    '전체 UI 글자 크기': '介面文字大小',
    '기본': '預設',
    '크게': '大',
    '더 크게': '特大',
    '개인정보': '隱私權',
    '앱 잠금': 'App 鎖定',
    'PIN 없이 잠금': '無 PIN 鎖定',
    'PIN 잠금': 'PIN 鎖定',
    '시스템 잠금 비밀번호': '系統驗證',
    '생체인식 잠금 해제': '生物辨識解鎖',
    '분류': '分類',
    '분류 추가': '新增分類',
    'AI 기능': 'AI 功能',
    '개발 중입니다.': '開發中。',
    '캘린더 데이터 옮기기': '匯入行事曆資料',
    '건너뛰기': '略過',
    '이전': '上一步',
    '다음': '下一步',
    '일정을 한눈에': '行程一目瞭然',
    '기록하고 바로 알림 받기': '記錄並立即接收提醒',
    '중요한 날까지 이어서': '掌握每個重要日子',
    'Daily 시작하기': '開始使用 Daily',
    'Apple로 계속': '使用 Apple 繼續',
    '로컬로 시작': '在本機開始',
    'Google 연결 중': '正在連接 Google',
    'Google로 계속': '使用 Google 繼續',
    '연결 취소': '取消連接',
    '알림 권한 허용': '允許通知',
    '검색': '搜尋',
    '필터': '篩選',
    '오늘': '今天',
    '빠른 보기': '快速檢視',
    '일정 추가': '新增行程',
    '일정 수정': '編輯行程',
    '저장': '儲存',
    '취소': '取消',
    '삭제': '刪除',
    '수정': '編輯',
    '제목': '標題',
    '시간': '時間',
    '장소': '地點',
    '메모': '備註',
    '종일': '全天',
    '반복': '重複',
    '없음': '無',
    '완료': '完成',
    '지도 바로가기': '在地圖中開啟',
    '월간 미니 캘린더': '月份迷你行事曆',
    '오늘 일정': '今日行程',
    '일정 없음': '沒有行程',
    '중요한 날짜': '重要日期',
    'D-day 일정 없음': '沒有 D-day 行程',
    '일정 {count}개': '{count} 個行程',
    'D-day {count}개': '{count} 個 D-day 行程',
    '공휴일 {count}개': '{count} 個國定假日',
    '검색 닫기': '關閉搜尋',
    '현재 보기에서 검색': '搜尋目前檢視',
    'D-day 일정만 보기': '僅顯示 D-day 行程',
    '공휴일 표시': '顯示國定假日',
    '분류 표시': '顯示分類',
    '검색어 지우기': '清除搜尋',
    'AI 입력 닫기': '關閉 AI 輸入',
    '일정을 입력하세요': '輸入行程',
    '등록': '新增',
    '이 일정으로 등록할까요?': '要新增此行程嗎？',
    '열기': '開啟',
    '추가 상세정보가 없습니다.': '沒有其他詳細資訊。',
    '주': '週',
    '개월': '個月',
    '년': '年',
    '번': '次',
    '제목을 입력하세요.': '請輸入標題。',
    '시작일': '開始日期',
    '종료일': '結束日期',
    '시작 시간': '開始時間',
    '종료 시간': '結束時間',
    '알림 직접 입력': '自訂提醒',
    '일정 알람': '行程鬧鐘',
    '종일 일정 알람 시각': '全天行程鬧鐘時間',
    'URL / 링크': 'URL / 連結',
    '날씨': '天氣',
    '예: 흐림': '例如：陰天',
    'D-day 표시': '顯示 D-day',
    '제목, 메모, 장소 검색': '搜尋標題、備註或地點',
    '검색 결과가 없습니다.': '沒有搜尋結果。',
    'Apple 연동 해지': '中斷 Apple 連結',
    'Google 연동 해지': '中斷 Google 連結',
    'D-day 알림': 'D-day 提醒',
    'Daily 계정': 'Daily 帳號',
    'Daily 버전': 'Daily 版本',
    'Google Drive 동기화': 'Google Drive 同步',
    'Google Drive에서 복원': '從 Google Drive 還原',
    'Google 계정': 'Google 帳號',
    'Google 로그인 시 Daily 계정에 연결됩니다.': '使用 Google 登入時會連結至 Daily 帳號。',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        '在此帳號的 Google Drive AppData 中備份及還原行程。',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        '沒有 Google 驗證工作階段。重新連結後會恢復自動同步。',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        '使用 Google 登入時也會要求 Drive AppData 存取權限。',
    '백업': '備份',
    'Google 다시 연결': '重新連結 Google',
    'Daily 계정 탈퇴': '刪除 Daily 帳號',
    '로컬 데이터 초기화': '重設本機資料',
    'Apple로 로그인됨': '已使用 Apple 登入',
    'Apple 로그인': 'Apple 登入',
    'Daily 계정에 연결된 Apple 로그인입니다.': '此 Apple 登入已連結至 Daily 帳號。',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.': '只使用 Apple 登入也能使用 Daily。',
    'Apple 또는 Google 계정을 연결할 수 있습니다.': '可以連結 Apple 或 Google 帳號。',
    '{providers} 로그인 연결됨': '已連結 {providers} 登入',
    '아직 동기화 기록이 없습니다.': '尚無同步記錄。',
    '백업 중': '正在備份',
    '복원 중': '正在還原',
    '동기화 중': '正在同步',
    '다른 기기 변경 확인 중': '正在檢查其他裝置的變更',
    '백업 완료': '備份完成',
    '복원 완료': '還原完成',
    '동기화 완료': '同步完成',
    '최신 상태': '已是最新狀態',
    '일부 백업 보류 · 먼저 복원 필요': '部分備份擱置・請先還原',
    '다른 기기 변경 확인 준비 중': '正在準備檢查其他裝置的變更',
    '동기화 완료 · 다른 기기 변경 복원': '同步完成・已還原其他裝置的變更',
    'PIN 확인': '驗證 PIN',
    '계속': '繼續',
    '기본 알림 직접 입력': '輸入預設提醒',
    '동기화 상태': '同步狀態',
    '로그아웃': '登出',
    '아침 브리핑': '晨間摘要',
    '알림 테스트': '測試通知',
    '복원': '還原',
    '분류 삭제': '刪除分類',
    '분류 수정': '編輯分類',
    '사용자 지정 색상': '自訂顏色',
    '시간 선택': '選擇時間',
    '시간 표시 방식': '時間格式',
    '시스템 알림 설정 열기': '開啟系統通知設定',
    '백업 삭제 후 해제': '刪除備份並中斷連結',
    '백업 없이 로그아웃': '不備份直接登出',
    '백업을 완료하지 못했습니다': '無法完成備份',
    '버그 제보': '回報問題',
    '보내기': '傳送',
    '연동 해지': '中斷連結',
    '연동만 해제': '僅中斷連結',
    '저장 내용 초기화': '刪除儲存資料',
    '적용': '套用',
    '직접 입력': '自訂',
    '잠금 방식 변경': '變更鎖定方式',
    '잠금 방식 선택': '選擇鎖定方式',
    '한 자리 지우기': '刪除一位數',
    '앱 정보': 'App 資訊',
    '일정이 시작됩니다.': '行程即將開始。',
    '일정 시작 {time}입니다.': '行程將於{time}開始。',
    'D-day 일정 알림입니다.': '這是 D-day 行程提醒。',
    '오늘의 일정': '今日行程',
    'Daily 알림 테스트': 'Daily 通知測試',
    '이 알림이 보이면 Daily의 알림 표시 권한은 정상입니다.': '若您看到此通知，表示 Daily 的通知權限正常。',
    '오늘 등록된 일정이 없습니다.': '今天沒有行程。',
    ' 외 {count}개 더 있습니다.': '，另有 {count} 個',
    '정시': '準時',
    '{count}분 전': '{count} 分鐘前',
    '{count}일 전': '{count} 天前',
    '{count}시간 전': '{count} 小時前',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': '輸入 PIN 以解除 App 鎖定。',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.': '此裝置無法使用系統驗證。',
    '기본 일정 알림': '預設行程提醒',
    '몇 분 전에 알릴까요?': '要提前幾分鐘提醒？',
    '종일 일정 알림 시간': '全天行程提醒時間',
    '종일 일정의 알림 기준 시간': '全天行程的預設提醒時間',
    '아침 브리핑 시간': '晨間摘要時間',
    '브리핑을 받을 시간': '接收摘要的時間',
    'D-day 알림 직접 입력': '自訂 D-day 提醒',
    'D-day 기준 일수. 예: -7, 0': '相對 D-day 的天數，例如 -7、0',
    '앱 잠금 PIN 설정': '設定 App 鎖定 PIN',
    '잠금 방식': '鎖定方式',
    '버전 {version} · 더블 클릭하여 Github 확인하기': '版本 {version}・按兩下查看 GitHub',
    '이름': '名稱',
    '색상': '顏色',
    '"{category}" 분류를 삭제할까요?': '要刪除「{category}」分類嗎？',
    '닫기': '關閉',
    '검색/필터': '搜尋／篩選',
    '반복 종료': '重複結束',
    '종료 없음': '永不',
    '날짜까지': '到指定日期',
    '횟수만큼': '指定次數',
    '반복 간격': '重複間隔',
    '몇 {unit}마다 반복할까요?': '每幾{unit}重複一次？',
    '반복 횟수': '重複次數',
    '몇 회 반복할까요?': '要重複幾次？',
    '제목을 입력해야 일정을 저장할 수 있습니다.': '請輸入標題後再儲存行程。',
    '종료일은 시작일과 같거나 이후여야 합니다.': '結束日期必須等於或晚於開始日期。',
    '종료 시간은 시작 시간보다 늦어야 합니다.': '結束時間必須晚於開始時間。',
    '반복 간격은 1 이상이어야 합니다.': '重複間隔必須至少為 1。',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.': '重複鬧鐘將於日後的例行功能中提供。',
    '알람 지원 상태를 확인하고 있습니다.': '正在檢查鬧鐘支援狀態。',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.': '此作業系統不支援行程鬧鐘。',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.': '請在系統設定中允許 Daily 使用鬧鐘。',
    '반복 일정 수정': '編輯重複行程',
    '반복 일정 삭제': '刪除重複行程',
    '일정 삭제': '刪除行程',
    '"{title}" 일정을 삭제할까요?': '要刪除「{title}」嗎？',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?': '要將{action}套用到此重複行程的哪個範圍？',
    '이 일정만': '僅此行程',
    '이후 일정': '此行程及之後',
    '전체 반복': '所有行程',
    '일정을 옮기는 중': '正在匯入行程',
    '{count}개 캘린더 가져오기': '匯入 {count} 個行事曆',
    '가져올 수 있는 {provider}가 없습니다.': '沒有可匯入的 {provider} 行事曆。',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        '匯入完成：新增 {imported} 個、略過 {skipped} 個重複項目、{failed} 個失敗',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.': '請檢查行事曆權限或連線狀態。',
    '가져올 캘린더를 선택해 주세요.': '請選擇要匯入的行事曆。',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.': '請在「設定」中允許 Daily 完整存取行事曆。',
    '캘린더 접근이 허용되지 않았습니다.': '未允許存取行事曆。',
    'Google 계정 로그인이 필요합니다.': '請先登入 Google 帳號。',
    'Google Calendar 응답 형식이 올바르지 않습니다.': 'Google Calendar 傳回了無效的回應。',
    '{title} 불러오기': '載入 {title}',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'App 鎖定時無法查看內容。',
    '잠금 상태입니다.': '已鎖定',
    'PIN 입력': '輸入 PIN',
    '비밀번호를 통해 잠금해제': '使用 PIN 解鎖',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.': '使用 Face ID、Touch ID 或裝置密碼驗證。',
    '시스템 잠금으로 해제': '使用系統驗證解鎖',
    'PIN이 일치하지 않습니다.': 'PIN 不相符。',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': '需要驗證才能解除 Daily 鎖定。',
    '시스템 인증을 완료하지 못했습니다.': '未能完成系統驗證。',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.': '未能完成生物辨識驗證，請輸入 PIN。',
    '일정이 없습니다.': '沒有行程。',
    '시작 시각 · 중지 또는 10분 후 다시 알림': '開始時間・停止或延後 10 分鐘提醒',
    '{time} · 중지 또는 10분 후 다시 알림': '{time}・停止或延後 10 分鐘提醒',
    'Apple 로그인 창을 여는 중입니다.': '正在開啟 Apple 登入。',
    'Apple 로그인이 취소되었습니다.': '已取消 Apple 登入。',
    'Apple 로그인이 완료되었습니다.': 'Apple 登入完成。',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Apple 登入完成，已恢復連結的 Google Drive 同步。',
    'Apple 연동을 해지했습니다.': '已中斷 Apple 連結。',
    'Google 로그인 창을 여는 중입니다.': '正在開啟 Google 登入。',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.': '已取消 Google Drive 連線，您可以重新連線。',
    '알림 권한 요청을 여는 중입니다.': '正在開啟通知權限要求。',
    '알림 권한 설정을 확인했습니다.': '已檢查通知權限設定。',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.': '離開 App 時隱藏內容，返回時自動解除。',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        '使用 Daily 專用 PIN 鎖定，也可選擇搭配生物辨識。',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.': '使用 Face ID、Touch ID 或裝置密碼驗證。',
    '알림 상태 확인 중입니다.': '正在檢查通知狀態。',
    '테스트 알림을 보냈습니다. {summary}': '已傳送測試通知。{summary}',
    '일정 알림, 아침 브리핑, D-day 알림': '行程提醒、晨間摘要與 D-day 提醒',
    'Apple, Google, 동기화 및 계정 관리': 'Apple、Google、同步與帳號管理',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.': '在月份行事曆的每個日期旁顯示農曆日期。',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.': '為清楚區分月份邊界，上下捲動時無法使用。',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.': '在月份行事曆的第一週與最後一週顯示相鄰月份。',
    '앱을 열었을 때 먼저 보여줄 달력 보기': '開啟 App 時先顯示的行事曆檢視',
    '앱을 다시 열 때 사용자를 확인합니다.': '重新開啟 App 時驗證使用者。',
    'AI': 'AI',
    'Gemini 사용': '使用 Gemini',
    '민감 문장 AI 차단': '阻擋敏感文字傳送至 AI',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.': '從 Apple 行事曆或 Google 日曆匯入。',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.': '從 Samsung 行事曆或 Google 日曆匯入。',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.': '使用月、週、日檢視快速聚焦需要的行程。',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.': '自然地記錄行程，並接收行程提醒與晨間摘要。',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        '使用 D-day 與分類，並透過 Google Drive 在多部裝置上接續使用。',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        '可連結 Apple 或 Google 帳號，或不使用帳號直接在本機開始。',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': '在行事曆與行程列表中顯示 D-day。',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.': '每天在指定時間顯示今日行程。',
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.': '使用預設瀏覽器開啟 GitHub 回報表單。',
    'GitHub Repository를 열 수 없습니다.': '無法開啟 GitHub 儲存庫。',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.': '無法開啟問題回報頁面，請稍後再試。',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?': '要繼續從目前的無 PIN 鎖定方式變更嗎？',
    '0 이상의 숫자를 입력하세요.': '請輸入大於或等於 0 的數字。',
    '{count} 이상의 숫자를 입력하세요.': '請輸入大於或等於 {count} 的數字。',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.': '請繼續輸入 PIN，或清除後重新輸入。',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        '使用 Touch ID 或 Apple Watch 解除 Daily PIN 鎖定。',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': '使用生物辨識解除 Daily PIN 鎖定。',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        '無法開啟通知設定，請在系統設定中允許 Daily 通知。',
    'Gemini API 키': 'Gemini API 金鑰',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        '在 Android 上，請前往「設定 > 應用程式 > Daily > 通知」允許通知。',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.': '全天行程會依照設定中的全天提醒時間排程。',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        '開啟後會要求 macOS 通知權限，並在開始時間傳送系統通知。',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.': '開啟後會要求鬧鐘權限，並以鬧鐘取代開始時間通知。',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '在選定時間傳送具備聲音與稍後提醒的 macOS 系統通知。',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '在開始時間傳送具備聲音與稍後提醒的 macOS 系統通知。',
    '선택한 시각에 시스템 알람이 울립니다.': '系統鬧鐘會在選定時間響起。',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.': '以系統鬧鐘取代開始時間通知。',
    'Google Drive 연결이 완료되었습니다.': 'Google Drive 連線完成。',
    'Google Drive 복원 완료': 'Google Drive 還原完成',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.': '無法完成要求，請稍後再試。',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.': '請檢查網路連線後再試。',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.': 'Google Drive 連線已過期，請重新連線。',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Drive 權限不足，請重新連線並允許存取。',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.': 'Google Drive 要求過多，請稍後再試。',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.': 'Google Drive 回應不穩定，請稍後再試。',
    'PIN 없음': '無 PIN',
    '시스템': '系統',
    '즉시 알림을 보내고 예약 상태를 확인합니다.': '立即傳送通知並檢查排程狀態。',
    'PIN은 4자리 이상이어야 합니다.': 'PIN 必須至少 4 位數。',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PIN 不相符，請重新輸入。',
    '마지막 성공: {time}': '上次成功：{time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.': '不會自動為新行程加入提醒。',
    'Apple 캘린더': 'Apple 行事曆',
    'Samsung 캘린더': 'Samsung 行事曆',
    'Google 캘린더': 'Google 日曆',
    '공휴일': '國定假日',
    '신정': '元旦',
    '삼일절': '三一節',
    '노동절': '勞動節',
    '어린이날': '兒童節',
    '현충일': '顯忠日',
    '제헌절': '制憲節',
    '광복절': '光復節',
    '개천절': '開天節',
    '한글날': '韓文日',
    '기독탄신일': '聖誕節',
    '설날 연휴': '春節連假',
    '설날': '春節',
    '부처님 오신 날': '佛誕日',
    '추석 연휴': '秋夕連假',
    '추석': '秋夕',
    '대체공휴일': '補假',
    '반복 없음': '不重複',
    '매일': '每天',
    '매주': '每週',
    '매월': '每月',
    '매년': '每年',
    '반복 종료일': '重複結束日期',
    '{count}회': '{count} 次',
    '{count}일마다': '每 {count} 天',
    '{count}주마다': '每 {count} 週',
    '{count}개월마다': '每 {count} 個月',
    '{count}년마다': '每 {count} 年',
    '{count}번마다': '每 {count} 次',
  },
};
